// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: grpc/CenturyGolemEdition.proto

package game_server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCardMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCardMessage) Reset() {
	*x = GetCardMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_CenturyGolemEdition_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCardMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardMessage) ProtoMessage() {}

func (x *GetCardMessage) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_CenturyGolemEdition_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardMessage.ProtoReflect.Descriptor instead.
func (*GetCardMessage) Descriptor() ([]byte, []int) {
	return file_grpc_CenturyGolemEdition_proto_rawDescGZIP(), []int{0}
}

type GemValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Yellow int32 `protobuf:"varint,1,opt,name=yellow,proto3" json:"yellow,omitempty"`
	Green  int32 `protobuf:"varint,2,opt,name=green,proto3" json:"green,omitempty"`
	Blue   int32 `protobuf:"varint,3,opt,name=blue,proto3" json:"blue,omitempty"`
	Pink   int32 `protobuf:"varint,4,opt,name=pink,proto3" json:"pink,omitempty"`
}

func (x *GemValue) Reset() {
	*x = GemValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_CenturyGolemEdition_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GemValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GemValue) ProtoMessage() {}

func (x *GemValue) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_CenturyGolemEdition_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GemValue.ProtoReflect.Descriptor instead.
func (*GemValue) Descriptor() ([]byte, []int) {
	return file_grpc_CenturyGolemEdition_proto_rawDescGZIP(), []int{1}
}

func (x *GemValue) GetYellow() int32 {
	if x != nil {
		return x.Yellow
	}
	return 0
}

func (x *GemValue) GetGreen() int32 {
	if x != nil {
		return x.Green
	}
	return 0
}

func (x *GemValue) GetBlue() int32 {
	if x != nil {
		return x.Blue
	}
	return 0
}

func (x *GemValue) GetPink() int32 {
	if x != nil {
		return x.Pink
	}
	return 0
}

type GemCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	In  *GemValue `protobuf:"bytes,1,opt,name=in,proto3" json:"in,omitempty"`
	Out *GemValue `protobuf:"bytes,2,opt,name=out,proto3" json:"out,omitempty"`
}

func (x *GemCard) Reset() {
	*x = GemCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_CenturyGolemEdition_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GemCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GemCard) ProtoMessage() {}

func (x *GemCard) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_CenturyGolemEdition_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GemCard.ProtoReflect.Descriptor instead.
func (*GemCard) Descriptor() ([]byte, []int) {
	return file_grpc_CenturyGolemEdition_proto_rawDescGZIP(), []int{2}
}

func (x *GemCard) GetIn() *GemValue {
	if x != nil {
		return x.In
	}
	return nil
}

func (x *GemCard) GetOut() *GemValue {
	if x != nil {
		return x.Out
	}
	return nil
}

type GolemCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cost  *GemValue `protobuf:"bytes,1,opt,name=cost,proto3" json:"cost,omitempty"`
	Value int32     `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GolemCard) Reset() {
	*x = GolemCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_CenturyGolemEdition_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GolemCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GolemCard) ProtoMessage() {}

func (x *GolemCard) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_CenturyGolemEdition_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GolemCard.ProtoReflect.Descriptor instead.
func (*GolemCard) Descriptor() ([]byte, []int) {
	return file_grpc_CenturyGolemEdition_proto_rawDescGZIP(), []int{3}
}

func (x *GolemCard) GetCost() *GemValue {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *GolemCard) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type CreateGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerCount int32 `protobuf:"varint,1,opt,name=player_count,json=playerCount,proto3" json:"player_count,omitempty"`
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_CenturyGolemEdition_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_CenturyGolemEdition_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_grpc_CenturyGolemEdition_proto_rawDescGZIP(), []int{4}
}

func (x *CreateGameRequest) GetPlayerCount() int32 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

type CreateGameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerCount int32        `protobuf:"varint,1,opt,name=player_count,json=playerCount,proto3" json:"player_count,omitempty"`
	GemLineup   []*GemCard   `protobuf:"bytes,2,rep,name=gem_lineup,json=gemLineup,proto3" json:"gem_lineup,omitempty"`
	GolemLineup []*GolemCard `protobuf:"bytes,3,rep,name=golem_lineup,json=golemLineup,proto3" json:"golem_lineup,omitempty"`
	PlayerGems  []*GemValue  `protobuf:"bytes,4,rep,name=player_gems,json=playerGems,proto3" json:"player_gems,omitempty"`
}

func (x *CreateGameResponse) Reset() {
	*x = CreateGameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_CenturyGolemEdition_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameResponse) ProtoMessage() {}

func (x *CreateGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_CenturyGolemEdition_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameResponse.ProtoReflect.Descriptor instead.
func (*CreateGameResponse) Descriptor() ([]byte, []int) {
	return file_grpc_CenturyGolemEdition_proto_rawDescGZIP(), []int{5}
}

func (x *CreateGameResponse) GetPlayerCount() int32 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

func (x *CreateGameResponse) GetGemLineup() []*GemCard {
	if x != nil {
		return x.GemLineup
	}
	return nil
}

func (x *CreateGameResponse) GetGolemLineup() []*GolemCard {
	if x != nil {
		return x.GolemLineup
	}
	return nil
}

func (x *CreateGameResponse) GetPlayerGems() []*GemValue {
	if x != nil {
		return x.PlayerGems
	}
	return nil
}

var File_grpc_CenturyGolemEdition_proto protoreflect.FileDescriptor

var file_grpc_CenturyGolemEdition_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x43, 0x65, 0x6e, 0x74, 0x75, 0x72, 0x79, 0x47, 0x6f,
	0x6c, 0x65, 0x6d, 0x45, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x10, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x60, 0x0a, 0x08, 0x47, 0x65, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x79,
	0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x79, 0x65, 0x6c,
	0x6c, 0x6f, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x65, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x67, 0x72, 0x65, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6c, 0x75,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x62, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x69, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x69, 0x6e,
	0x6b, 0x22, 0x59, 0x0a, 0x07, 0x47, 0x65, 0x6d, 0x43, 0x61, 0x72, 0x64, 0x12, 0x25, 0x0a, 0x02,
	0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x02, 0x69, 0x6e, 0x12, 0x27, 0x0a, 0x03, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47,
	0x65, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x03, 0x6f, 0x75, 0x74, 0x22, 0x4c, 0x0a, 0x09,
	0x47, 0x6f, 0x6c, 0x65, 0x6d, 0x43, 0x61, 0x72, 0x64, 0x12, 0x29, 0x0a, 0x04, 0x63, 0x6f, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x04,
	0x63, 0x6f, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x36, 0x0a, 0x11, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x21, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0xdf, 0x01, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x33, 0x0a, 0x0a,
	0x67, 0x65, 0x6d, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x75, 0x70, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47,
	0x65, 0x6d, 0x43, 0x61, 0x72, 0x64, 0x52, 0x09, 0x67, 0x65, 0x6d, 0x4c, 0x69, 0x6e, 0x65, 0x75,
	0x70, 0x12, 0x39, 0x0a, 0x0c, 0x67, 0x6f, 0x6c, 0x65, 0x6d, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x75,
	0x70, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x6f, 0x6c, 0x65, 0x6d, 0x43, 0x61, 0x72, 0x64, 0x52,
	0x0b, 0x67, 0x6f, 0x6c, 0x65, 0x6d, 0x4c, 0x69, 0x6e, 0x65, 0x75, 0x70, 0x12, 0x36, 0x0a, 0x0b,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x67, 0x65, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x47, 0x65, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x47, 0x65, 0x6d, 0x73, 0x32, 0x46, 0x0a, 0x04, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x3e, 0x0a, 0x07,
	0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x12, 0x1b, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x1a, 0x14, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x47, 0x65, 0x6d, 0x43, 0x61, 0x72, 0x64, 0x22, 0x00, 0x42, 0x62, 0x0a, 0x22,
	0x64, 0x65, 0x76, 0x2e, 0x6b, 0x68, 0x79, 0x6d, 0x61, 0x6e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x63, 0x65, 0x6e, 0x74, 0x75, 0x72, 0x79, 0x2d, 0x67, 0x6f, 0x6c, 0x65, 0x6d, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x42, 0x11, 0x43, 0x65, 0x6e, 0x74, 0x75, 0x72, 0x79, 0x47, 0x6f, 0x6c, 0x65, 0x6d,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x29, 0x6b, 0x68, 0x79, 0x6d, 0x61, 0x6e, 0x2e, 0x64, 0x65,
	0x76, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x65, 0x6e, 0x74, 0x75, 0x72, 0x79, 0x2d, 0x67,
	0x6f, 0x6c, 0x65, 0x6d, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_CenturyGolemEdition_proto_rawDescOnce sync.Once
	file_grpc_CenturyGolemEdition_proto_rawDescData = file_grpc_CenturyGolemEdition_proto_rawDesc
)

func file_grpc_CenturyGolemEdition_proto_rawDescGZIP() []byte {
	file_grpc_CenturyGolemEdition_proto_rawDescOnce.Do(func() {
		file_grpc_CenturyGolemEdition_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_CenturyGolemEdition_proto_rawDescData)
	})
	return file_grpc_CenturyGolemEdition_proto_rawDescData
}

var file_grpc_CenturyGolemEdition_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_grpc_CenturyGolemEdition_proto_goTypes = []interface{}{
	(*GetCardMessage)(nil),     // 0: game_server.GetCardMessage
	(*GemValue)(nil),           // 1: game_server.GemValue
	(*GemCard)(nil),            // 2: game_server.GemCard
	(*GolemCard)(nil),          // 3: game_server.GolemCard
	(*CreateGameRequest)(nil),  // 4: game_server.CreateGameRequest
	(*CreateGameResponse)(nil), // 5: game_server.CreateGameResponse
}
var file_grpc_CenturyGolemEdition_proto_depIdxs = []int32{
	1, // 0: game_server.GemCard.in:type_name -> game_server.GemValue
	1, // 1: game_server.GemCard.out:type_name -> game_server.GemValue
	1, // 2: game_server.GolemCard.cost:type_name -> game_server.GemValue
	2, // 3: game_server.CreateGameResponse.gem_lineup:type_name -> game_server.GemCard
	3, // 4: game_server.CreateGameResponse.golem_lineup:type_name -> game_server.GolemCard
	1, // 5: game_server.CreateGameResponse.player_gems:type_name -> game_server.GemValue
	0, // 6: game_server.Game.GetCard:input_type -> game_server.GetCardMessage
	2, // 7: game_server.Game.GetCard:output_type -> game_server.GemCard
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_grpc_CenturyGolemEdition_proto_init() }
func file_grpc_CenturyGolemEdition_proto_init() {
	if File_grpc_CenturyGolemEdition_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_CenturyGolemEdition_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCardMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_CenturyGolemEdition_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GemValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_CenturyGolemEdition_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GemCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_CenturyGolemEdition_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GolemCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_CenturyGolemEdition_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_CenturyGolemEdition_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_CenturyGolemEdition_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_CenturyGolemEdition_proto_goTypes,
		DependencyIndexes: file_grpc_CenturyGolemEdition_proto_depIdxs,
		MessageInfos:      file_grpc_CenturyGolemEdition_proto_msgTypes,
	}.Build()
	File_grpc_CenturyGolemEdition_proto = out.File
	file_grpc_CenturyGolemEdition_proto_rawDesc = nil
	file_grpc_CenturyGolemEdition_proto_goTypes = nil
	file_grpc_CenturyGolemEdition_proto_depIdxs = nil
}
